apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redirect
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: redirect
    repoURL: https://github.com/ncr-payment-solutions/payment-redirect-deploy.git
    targetRevision: HEAD
    
