apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ach-validation-service
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ach-deploy
    repoURL: https://github.com/ncr-payment-solutions/GOV-ACH-Account-Validation-Service--deploy.git
    targetRevision: HEAD

    
